### ISSUE TITLE
[Bug]  VSCode complain cant read or find certain snippet file

### ISSUE THREAD

**Issue by mo-azfar** [dennykorsukewitz/DK4Znuny-VisualStudioCode#7]
# Bug report

When executing certain snippet autocomplete, the Developer Tools complain about missing file. 
Im noticed the different filename from https://github.com/dennykorsukewitz/VSCode-Znuny/tree/dev/snippets/DynamicFields

Log as below

` ERR sa: Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.DateTime.code-snippets' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.DateTime.code-snippets')
    at Pnt.F (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69674)
    at Pnt.D (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69499)
    at async Pnt.C (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:68867)
    at async Wrt.readExtensionResource (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3114:2109) vscode-remote://ssh-remote%2B7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.DateTime.code-snippets
log.ts:439   ERR sa: Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.Dropdown.code-snippets' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.Dropdown.code-snippets')
    at Pnt.F (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69674)
    at Pnt.D (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69499)
    at async Pnt.C (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:68867)
    at async Wrt.readExtensionResource (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3114:2109) vscode-remote://ssh-remote%2B7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.Dropdown.code-snippets
log.ts:439   ERR sa: Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.Multiselect.code-snippets' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.Multiselect.code-snippets')
    at Pnt.F (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69674)
    at Pnt.D (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69499)
    at async Pnt.C (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:68867)
    at async Wrt.readExtensionResource (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3114:2109) vscode-remote://ssh-remote%2B7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.Multiselect.code-snippets
log.ts:439   ERR sa: Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.Text.code-snippets' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.Text.code-snippets')
    at Pnt.F (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69674)
    at Pnt.D (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69499)
    at async Pnt.C (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:68867)
    at async Wrt.readExtensionResource (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3114:2109) vscode-remote://ssh-remote%2B7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.Text.code-snippets
log.ts:439   ERR sa: Unable to read file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.TextArea.code-snippets' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.TextArea.code-snippets')
    at Pnt.F (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69674)
    at Pnt.D (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:69499)
    at async Pnt.C (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3088:68867)
    at async Wrt.readExtensionResource (vscode-file://vscode-app/c:/Users/budak/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3114:2109) vscode-remote://ssh-remote%2B7b22686f73744e616d65223a224566666c7578446576227d/root/.vscode-server/extensions/dennykorsukewitz.znuny-1.4.1/snippets/DynamicFields/znuny.DynamicField.TextArea.code-snippets`

## How to reproduce

1. Execute any znuny snippet in editor
2. Go to Menu bar > Help > Toggle Developer Tools
3. See error

## Screenshots

![image](https://github.com/user-attachments/assets/87f72e8d-f2af-4716-acdf-3caa7c52aca3)

## Environment

- OS Client: Windows 11
- OS Server: Ubuntu 22 
- VSC Version: 1.95.3

## Additional information

At this point, im not sure its really a bug or just need to clear some kind of vscode cache..
but thanks

**Comment by dennykorsukewitz** [comment]
Hi @mo-azfar,
thanks for your report.

I could not reproduce the error the way you described it. But I have corrected the names and that should fix the error in the next version.

Regards :rocket:
Denny
